CREATE TABLE items (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    item_type VARCHAR(50) NOT NULL
);

CREATE TABLE locations (
    id SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DISPLAY_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE regions (
    id SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DISPLAY_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE entrances (
    id SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DISPLAY_NAME VARCHAR(255) NOT NULL,
    ENTRANCE_TYPE VARCHAR(50) NOT NULL
);