CREATE TABLE runs (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    data jsonb,
    accessed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);