ALTER TABLE runs
    ALTER COLUMN accessed_at TYPE TIMESTAMPTZ USING accessed_at AT TIME ZONE 'UTC',
    ALTER COLUMN modified_at TYPE TIMESTAMPTZ USING modified_at AT TIME ZONE 'UTC',
    ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at AT TIME ZONE 'UTC';