DELETE FROM item_type;

INSERT INTO public.item_type (name, display_name) VALUES ('rupees', 'Rupees');
INSERT INTO public.item_type (name, display_name) VALUES ('royal_wallet', 'Royal Wallet');
INSERT INTO public.item_type (name, display_name) VALUES ('navigation', 'Navigation');
INSERT INTO public.item_type (name, display_name) VALUES ('magic_powers', 'Magic Powers');
INSERT INTO public.item_type (name, display_name) VALUES ('magic_jars', 'Magic Jars');
INSERT INTO public.item_type (name, display_name) VALUES ('potions', 'Potions');
INSERT INTO public.item_type (name, display_name) VALUES ('stray_fairies', 'Stray Fairies');
INSERT INTO public.item_type (name, display_name) VALUES ('fairy', 'Fairy');
INSERT INTO public.item_type (name, display_name) VALUES ('masks', 'Masks');
INSERT INTO public.item_type (name, display_name) VALUES ('deku_sticks', 'Deku Sticks');
INSERT INTO public.item_type (name, display_name) VALUES ('deku_nuts', 'Deku Nuts');
INSERT INTO public.item_type (name, display_name) VALUES ('milk', 'Milk');
INSERT INTO public.item_type (name, display_name) VALUES ('songs', 'Songs');
INSERT INTO public.item_type (name, display_name) VALUES ('fake', 'Fake');
INSERT INTO public.item_type (name, display_name) VALUES ('chateau', 'Chateau');
INSERT INTO public.item_type (name, display_name) VALUES ('scooped_items', 'Scooped Items');
INSERT INTO public.item_type (name, display_name) VALUES ('boss_remains', 'Boss Remains');
INSERT INTO public.item_type (name, display_name) VALUES ('trade_items', 'Trade Items');
INSERT INTO public.item_type (name, display_name) VALUES ('frogs', 'Frogs');
INSERT INTO public.item_type (name, display_name) VALUES ('arrows', 'Arrows');
INSERT INTO public.item_type (name, display_name) VALUES ('bombchu', 'Bombchu');
INSERT INTO public.item_type (name, display_name) VALUES ('notebook_entries', 'Notebook Entries');
INSERT INTO public.item_type (name, display_name) VALUES ('dungeon_keys', 'Dungeon Keys');
INSERT INTO public.item_type (name, display_name) VALUES ('bombs', 'Bombs');
INSERT INTO public.item_type (name, display_name) VALUES ('seahorse', 'Seahorse');
INSERT INTO public.item_type (name, display_name) VALUES ('recovery_hearts', 'Recovery Hearts');
INSERT INTO public.item_type (name, display_name) VALUES ('skulltula_tokens', 'Skulltula Tokens');
INSERT INTO public.item_type (name, display_name) VALUES ('shields', 'Shields');
INSERT INTO public.item_type (name, display_name) VALUES ('heart_containers', 'Heart Containers');
INSERT INTO public.item_type (name, display_name) VALUES ('main_inventory', 'Main Inventory');
INSERT INTO public.item_type (name, display_name) VALUES ('pieces_of_heart', 'Pieces of Heart');
